// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMoLOxiMxKezR46REl5t_FOhGyRKylafY',
    appId: '1:333002479535:web:655d723cce1f3445d4815a',
    messagingSenderId: '333002479535',
    projectId: 'admin-349a7',
    authDomain: 'admin-349a7.firebaseapp.com',
    storageBucket: 'admin-349a7.appspot.com',
    measurementId: 'G-PYREGPDLWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-BX66vvmI_ZZKlEzlevPTuT-Z7V7sDAk',
    appId: '1:333002479535:android:701658dbf94b371fd4815a',
    messagingSenderId: '333002479535',
    projectId: 'admin-349a7',
    storageBucket: 'admin-349a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0sTMBssbhdBms2zqbXMJ2VKhbQeCtDxc',
    appId: '1:333002479535:ios:1565cb126f17d9add4815a',
    messagingSenderId: '333002479535',
    projectId: 'admin-349a7',
    storageBucket: 'admin-349a7.appspot.com',
    iosBundleId: 'com.example.admin',
  );
}
